.PHONY: test build check clean

test:
	./gradlew test

build:
	./gradlew clean build

check:
	./gradlew check

clean:
	./gradlew clean

sonar:
	./gradlew sonar

run:
	./gradlew run
